name: Release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  release:
    runs-on: macos-latest
    environment: build
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Darwin
      run: |
        GOOS=darwin GOARCH=amd64 go build -o interpreter ./cmd/interpreter/main.go
        zip interpreter-darwin-amd64.zip interpreter

    - name: Build Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o interpreter.exe ./cmd/interpreter/main.go
        zip interpreter-windows-amd64.zip interpreter.exe

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "interpreter-darwin-amd64.zip,interpreter-windows-amd64.zip"
        token: ${{ secrets.GH_ACCESS_TOKEN }}
